[package]
name = "mrd-signal-proto"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
mrd-identity = { path = "../mrd-identity" }
mrd-proto = { path = "../mrd-proto" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
ring.workspace = true
