pub mod av1_d3d11va;
pub mod av1_d3d12va;
pub mod av1_dxva2;
pub mod av1_qsv;
pub mod av1_software;
pub mod cuda;
pub mod d3d11;
pub mod d3d11va;
pub mod d3d12va;
pub mod dnxhd_software;
pub mod dnxhr_software;
pub mod dxva2;
pub mod gpu_proto;
pub mod h264_cuda;
pub mod h264_d3d11va;
pub mod h264_d3d12va;
pub mod h264_dxva2;
pub mod h264_qsv;
pub mod h264_software;
pub mod h264_vaapi;
pub mod hevc_cuda;
pub mod hevc_d3d11va;
pub mod hevc_d3d12va;
pub mod hevc_dxva2;
pub mod hevc_qsv;
pub mod hevc_software;
pub mod hevc_vaapi;
pub mod metal;
pub mod mjpeg_software;
pub mod opencl;
pub mod prores_software;
pub mod qsv;
pub mod software;
pub mod vaapi;
pub mod vp9_software;
pub mod vulkan;

pub fn decode_work_us(name: &str) -> Option<u64> {
    match name {
        "gpu_proto" => Some(gpu_proto::decode_work_us()),
        "software" => Some(software::decode_work_us()),
        "h264_software" => Some(h264_software::decode_work_us()),
        "hevc_software" => Some(hevc_software::decode_work_us()),
        "av1_software" => Some(av1_software::decode_work_us()),
        "vp9_software" => Some(vp9_software::decode_work_us()),
        "mjpeg_software" => Some(mjpeg_software::decode_work_us()),
        "prores_software" => Some(prores_software::decode_work_us()),
        "dnxhd_software" => Some(dnxhd_software::decode_work_us()),
        "dnxhr_software" => Some(dnxhr_software::decode_work_us()),
        "h264_cuda" => Some(h264_cuda::decode_work_us()),
        "h264_d3d12va" => Some(h264_d3d12va::decode_work_us()),
        "h264_d3d11va" => Some(h264_d3d11va::decode_work_us()),
        "h264_dxva2" => Some(h264_dxva2::decode_work_us()),
        "h264_qsv" => Some(h264_qsv::decode_work_us()),
        "h264_vaapi" => Some(h264_vaapi::decode_work_us()),
        "hevc_cuda" => Some(hevc_cuda::decode_work_us()),
        "hevc_d3d12va" => Some(hevc_d3d12va::decode_work_us()),
        "hevc_d3d11va" => Some(hevc_d3d11va::decode_work_us()),
        "hevc_dxva2" => Some(hevc_dxva2::decode_work_us()),
        "hevc_qsv" => Some(hevc_qsv::decode_work_us()),
        "hevc_vaapi" => Some(hevc_vaapi::decode_work_us()),
        "av1_d3d11va" => Some(av1_d3d11va::decode_work_us()),
        "av1_d3d12va" => Some(av1_d3d12va::decode_work_us()),
        "av1_dxva2" => Some(av1_dxva2::decode_work_us()),
        "av1_qsv" => Some(av1_qsv::decode_work_us()),
        "d3d11" => Some(d3d11::decode_work_us()),
        "d3d11va" => Some(d3d11va::decode_work_us()),
        "d3d12va" => Some(d3d12va::decode_work_us()),
        "dxva2" => Some(dxva2::decode_work_us()),
        "cuda" => Some(cuda::decode_work_us()),
        "metal" => Some(metal::decode_work_us()),
        "opencl" => Some(opencl::decode_work_us()),
        "qsv" => Some(qsv::decode_work_us()),
        "vaapi" => Some(vaapi::decode_work_us()),
        "vulkan" => Some(vulkan::decode_work_us()),
        _ => None,
    }
}
